### ISSUE TITLE
Pressing second start doesnt start game

### ISSUE THREAD

**Issue by Ry3yr** [Mugen87/nier#11]
Browsers: Chrome , Opera
________

Sadly on an android tablet,
the game will not proceed after pressing the second start (click sound can be heard tho)

Feature suggestion at this point:
Add autofire and "move on hover"
=> that way s6lite esque devices w.o keyboard could still play it

**Comment by Mugen87** [comment]
The showcase hasn't been developed for tables (or touch devices) in general since it relies on the Pointer Lock API. This Web API isn't available for touch devices.

Besides, without a mouse or gamepad you can't control the player anyway. So I'm afraid this is a `Won't fix`.
